### ISSUE TITLE
Default values for scalar arguments passed as string

### ISSUE THREAD

**Issue by ichorid** [strawberry-graphql/strawberry#3158] opened 2023-10-18 09:52 UTC
When declaring an optional argument with a scalar type, its default value is passed as a string in the resulting schema. This makes Strawberry-declared schemas incompatible with externally connected GraphQL consumers with strict schema checkers, such as Hasura.

The following code:
```python
from typing import Optional

import strawberry


@strawberry.type
class Query:
    @strawberry.field
    def example(self,
                baz: int,
                foo: int | None = None ,
                bar: int = 10
                ) -> None:
        return None


schema = strawberry.Schema(query=Query)
```

produces the following default values in the schema:
```
...
                  "defaultValue": null
...
                  "defaultValue": "null"
...
                  "defaultValue": "10"
```

<details> 
<summary> Schema inspection </summary>

```graphql
{
  "data": {
    "__schema": {
      "queryType": {
        "name": "Query"
      },
      "mutationType": null,
      "types": [
        {
          "kind": "OBJECT",
          "name": "Query",
          "description": null,
          "fields": [
            {
              "name": "example",
              "description": null,
              "args": [
                {
                  "name": "baz",
                  "description": null,
                  "type": {
                    "kind": "NON_NULL",
                    "name": null,
                    "ofType": {
                      "kind": "SCALAR",
                      "name": "Int",
                      "ofType": null
                    }
                  },
                  "defaultValue": null
                },
                {
                  "name": "foo",
                  "description": null,
                  "type": {
                    "kind": "SCALAR",
                    "name": "Int",
                    "ofType": null
                  },
                  "defaultValue": "null"
                },
                {
                  "name": "bar",
                  "description": null,
                  "type": {
                    "kind": "NON_NULL",
                    "name": null,
                    "ofType": {
                      "kind": "SCALAR",
                      "name": "Int",
                      "ofType": null
                    }
                  },
                  "defaultValue": "10"
                }
```

</details>

## System Information
Python 3.11
Ubuntu 22.10
Strawberry version: 0.209.2

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/strawberry-graphql) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/strawberry-graphql/strawberry/issues/3158">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3158/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/strawberry-graphql/strawberry/issues/3158/pledge.svg">
</picture>
</a>

**Comment by krispharper** [comment] 2024-05-15 12:20
Would love to know if this is fixable. We just ran into this issue as well. We have a Java client that fails introspection of our Strawberry APIs because some default int values are strings instead of ints.

**Comment by patrick91** [comment] 2024-05-15 12:29
@krispharper can you show us the error?

I've made a reproduction for this: https://play.strawberry.rocks/?gist=482103631096241ca1a08f95aeed655a

But to clarify, this behaviour is from [GraphQL core](https://github.com/graphql-python/graphql-core) and we don't have a lot of control over it 😊

Also I think the spec allows this: https://spec.graphql.org/October2021/#sec-The-__InputValue-Type (but I might have read it wrong :) )

**Comment by erikwrede** [comment] 2024-05-17 12:10
@krispharper can you share the client implementation you're using?
I'm with Patrick on this one. The type of `__InputValue.defaultValue` is string:
```graphql
type __InputValue {
  name: String!
  description: String
  type: __Type!
  defaultValue: String
}
```
Source: Schema introspection schema, GraphQL Spec: https://spec.graphql.org/October2021/#sec-Schema-Introspection.Schema-Introspection-Schema

This is a bug that needs to be raised with the individual libraries not following the spec.

**Comment by x0y-gt** [comment] 2024-08-06 16:30
I just ran into this as well, any possible solutions?
I'm trying to connect my graphql api to hasura

**Comment by erikwrede** [comment] 2024-10-23 17:07
@x0y-gt great to hear you found a workaround for your case.
> This avoids issues like "true" being treated as a string instead of a boolean.
I just want to reiterate that this is not an issue and actually the way it is intended by the spec. See https://spec.graphql.org/October2021/#sec-Schema-Introspection.Schema-Introspection-Schema for the GraphQL schema for introspection. The Type [__InputValue](https://spec.graphql.org/October2021/#sel-GAJXNFADgHAAD8HABj2I) has a field `defaultValue` of type `String`. 
Values of any type other than string (such as true) are actually not spec-compliant. Closing this, since this is a bug in the consumer libraries rather than strawberry or GraphQL-Core.

**Closed by erikwrede** 2024-10-23 17:07 UTC
Labels: bug
