### ISSUE TITLE
Forward annotations might be treated as void sometimes

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#1879] opened 2022-05-03 16:34 UTC
We just had this bug report on discord:

```
Quick question: if I am running into a circular dependency, I thought I could specify the return type of a resolver as a string? something like:
@strawberry.field
def user(self) -> "Artist":
   ...

but, when querying the subfields of artist in a query, I get:
"Field 'user' must not have a selection since type 'Void' has no subfields.",
```

It feels like "Artist" was treated as `None` (thus becoming void in the schema), we should prevent this from happening.

**Comment by skilkis** [comment] 2022-05-09 19:48
@patrick91 I cannot reproduce this bug, there are explicit tests to cover forward references and both cases below function as expected on `v0.111.1` of Strawberry

### Case 1: Forward reference resolved from module scope
```python
import strawberry


@strawberry.type
class Query:
    @strawberry.field
    def actor(self) -> "Actor":
        return Actor()


@strawberry.type
class Actor:

    name: str = strawberry.field(default="Mark Hamill")


schema = strawberry.Schema(query=Query)

print(schema.execute_sync("{ actor  { name }}"))

```
Output:
```python
ExecutionResult(data={'actor': {'name': 'Mark Hamill'}}, errors=None, extensions={})
```

### Case 2: Forward reference fails (due to nesting) and proper error is raised
```python
import strawberry

def nested_scope():
    @strawberry.type
    class Query:
        @strawberry.field
        def actor(self) -> "Actor":
            return Actor()

    @strawberry.type
    class Actor:

        name: str = strawberry.field(default="Mark Hamill")

    schema = strawberry.Schema(query=Query)

    print(schema.execute_sync("{ actor  { name }}"))


nested_scope()

```
Output:
```bash
TypeError: Query fields cannot be resolved. Could not resolve the type of 'actor'. Check that the class is accessible from the global module scope.
```

**Comment by skilkis** [comment] 2022-05-12 08:09
If anyone is able to reproduce this bug please tag me here, so that I can fix it 😊

**Comment by benzolium** [comment] 2022-06-30 05:33
@skilkis I was able to reproduce while using `TYPE_CHECKING` to deal with a circular dependency:

`helpers.py`
```python
import strawberry


@strawberry.type
class Actor:

    name: str = strawberry.field(default="Mark Hamill")
```

`schema.py`
```python

import strawberry
import typing as tp

if tp.TYPE_CHECKING:
    from helpers import Actor


@strawberry.type
class Query:
    @strawberry.field
    def actor(self) -> tp.Optional['Actor']:
        return None


schema = strawberry.Schema(query=Query)

print(schema.execute_sync("{ actor  { name }}"))
```

Got:
```
TypeError: Query fields cannot be resolved. Could not resolve the type of 'actor'. Check that the class is accessible from the global module scope.
```

`strawberry==0.114.2`

**Comment by skilkis** [comment] 2022-06-30 07:53
@benzolium thanks for submitting this issue! In this case you may use `LazyType` as follows:

```python
import strawberry
import typing as tp

from strawberry.lazy_type import LazyType

if tp.TYPE_CHECKING:
    from helpers import Actor
else:
    # Defining the LazyType here ensures that type-checking uses the actual Actor type
    Actor = LazyType(type_name="Actor", module="helpers", package=None)


@strawberry.type
class Query:
    @strawberry.field
    def actor(self) -> tp.Optional[Actor]:
        return None


schema = strawberry.Schema(query=Query)

print(schema.execute_sync("{ actor  { name }}"))
```

Output:
```shell
ExecutionResult(data={'actor': None}, errors=None, extensions={})
```

On a side-note I tried to think of solutions of how to support types declared in a `TYPE_CHECKING` block. In my opinion this would be problematic to support because the current approach to resolving postponed annotations is to eval them within the module-level scope where the resolver is defined. Since anything defined in the `TYPE_CHECKING` block is not available at runtime, the only option is to perform static analysis of the module to resolve the definition location of the type. This would be quite costly as compared to using `LazyType`. [PEP-649](https://peps.python.org/pep-0649/) is discussing how resolve these [circular dependencies](https://peps.python.org/pep-0649/#circular-imports) but have not reached a consensus.

**Comment by benzolium** [comment] 2022-06-30 08:04
@skilkis thanks a lot! Works like a charm. 🙂

**Closed** 2022-07-28 22:07 UTC
Labels: bug
