### ISSUE TITLE
mutation

### ISSUE THREAD

**Issue by musavirchukkan** [strawberry-graphql/strawberry#213] opened 2019-11-16 15:42 UTC
It would be great to have a way to specify permissions for a mutation, something similar to what we did for the fields

**Comment by musavirchukkan** [comment] 2019-11-16 15:43
It would be great to have a way to specify permissions for a mutation, something similar to what we did for the fields

**Comment by jaydenwindle** [comment] 2019-11-16 19:42
Hey @musavirchukkan! This looks like a duplicate of #112, so I'm going to close it for now. Please have a look at the solution proposed there and let me know if that works for you.

**Closed by jaydenwindle** 2019-11-16 19:42 UTC
