### ISSUE TITLE
Strawberry cli commands fail with error: strawberry.exe\__main__.py not found

### ISSUE THREAD

**Issue by gauthamkamath** [strawberry-graphql/strawberry#2469] opened 2023-01-18 17:57 UTC
After upgrading strawberry to latest version (0.154.1), I am unable to run any strawberry cli commands.

## Describe the Bug
- Upgraded strawberry from 0.152.0 to 0.154.1
```
poetry add strawberry-graphql[debug-server]@0.154.1
```
- Executed below commands:
```
strawberry server myapp.schema
strawberry export-schema myapp.schema:schema
```
- Both these commands are failing in below error:

**FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\myyuser\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\straw-k47ybk7v-py3.10\\Scripts\\strawberry.exe\\\_\_main\_\_.py'**

## System Information

 - Operating system: Windows 10
 - Strawberry version (if applicable): 0.154.1
 - Python: 3.10.9

## Additional Context

There is no issue with strawberry cli in version 0.152.0 which I am using currently. If we downgrade the package to this version, cli commands work just fine.

**Comment by skilkis** [comment] 2023-01-18 18:58
@gauthamkamath unfortunately I was not able to reproduce this bug on my system. 

Operating system: Windows 10
Strawberry version (if applicable): 0.154.1
Python: 3.9.13

Could you try the following?

1. Create a new directory for testing
2. Run `python -m venv .venv`
3. Activate venv (assuming powershell): `env/Scripts/Activate.ps1`
4. Upgrade pip, install poetry, and configure config to use venv.
    ```shell
    python -m pip install --upgrade pip
    pip install poetry
    poetry config virtualenvs.prefer-active-python true
    ```
5. Initialize project `poetry init`
6. Add Strawberry dependency: `poetry add strawberry-graphql[debug-server]@0.154.1`
7. Create a `app.py` file with the following contents:
    ```python
    import strawberry
    
    @strawberry.type
    class Query:
    
        foo: str
    
    schema = strawberry.Schema(Query)
    ```
8. Run strawberry server and export-schema:
    ```shell
    strawberry server app
    strawberry export-schema app
    ```

**Comment by gauthamkamath** [comment] 2023-01-20 08:35
Hi @skilkis , your code works perfectly fine with version: 0.154.1 . 
But I am getting the same issue when I try running with this code: <https://github.com/gauthamkamath/straw.git> (same code as <https://github.com/strawberry-graphql/strawberry/issues/2397#issuecomment-1381711431>)
Could you please have a look?

**Comment by skilkis** [comment] 2023-01-21 12:23
@gauthamkamath I'll check out your code tomorrow, thanks for the link 😊

**Comment by skilkis** [comment] 2023-02-06 04:35
@gauthamkamath thank you for your patience, I've implemented a fix for this in https://github.com/strawberry-graphql/strawberry/pull/2512. Hope we can ship that out soon for you

**Closed** 2023-02-06 22:26 UTC
Labels: bug
