### ISSUE TITLE
context on Subscription Info object does not bring custom headers from GraphiQL

### ISSUE THREAD

**Issue by krauss** [strawberry-graphql/strawberry#2351] opened 2022-11-16 19:53 UTC
## Describe the Bug

Custom headers sent through GraphiQL interface don't come up within the Info object (`info.context['request'].headers.items()`) of a Subscription. However, they do come up when you run a Query. Am I missing something here or is this really a bug?

## System Information

 - Operating system: Fedora Linux 36
 - Strawberry version (if applicable): 0.142.2
 - FastAPI version: 0.87.0
 - Starlette version: 0.21.0
 - Uvicorn version: 0.19.0

## Additional Context

The chunk of code below can be used to reproduce the scenario.

```python
# std lib imports
import asyncio
from typing import AsyncGenerator

# 3rd imports
import strawberry
from fastapi import FastAPI
from strawberry.fastapi import GraphQLRouter
from strawberry.schema.config import StrawberryConfig
from strawberry.types import Info

#-----------------------------------------------------------------------------
@strawberry.type
class Subscription:

    @strawberry.subscription
    async def count(self, info: Info, target: int = 100) -> AsyncGenerator[str, None]:
        for i in range(target):
            yield f"Counting {i} - headers: {info.context['request'].headers.items()}"
            await asyncio.sleep(0.5)


@strawberry.type
class Query:

    @strawberry.field
    async def say_hi(self, info: Info, name: str) -> str:
        return f"Hi {name}, here are your custom headers: {info.context['request'].headers.items()}"

#-----------------------------------------------------------------------------
schema = strawberry.Schema(
    query=Query, 
    subscription=Subscription, 
    config=StrawberryConfig(auto_camel_case=False))
graphql_api = GraphQLRouter(schema)

app = FastAPI(title='UpData - GraphQL API')
app.include_router(graphql_api, prefix='/graphql')
app.add_websocket_route("/graphql", graphql_api)
```

**Comment by krauss** [comment] 2022-11-22 14:56
> Unrelated to the post, but does subscriptions work for you at all now?

Yes it does. By the way, I am using python 3.11  as well. There is one dependency you must install in order for Subscriptions to work. It is the websockets lib.

`pip install websockets`

**Comment by DoctorJohn** [comment] 2022-11-29 17:19
After a quick investigation I feel like this could be specific to the fastapi integration. @tsmith023 do you have an idea what's happening? Asking because it looks like you worked on the related code a lot and I'm slightly overwhelmed by the `__get_context_getter` method :)

**Comment by tsmith023** [comment] 2022-11-29 18:11
Thanks for bringing me into this one @DoctorJohn :grin:

This reminds me of an issue that I saw a few weeks back: https://github.com/strawberry-graphql/strawberry/issues/2021, so I wonder if the same problem is occurring here.

Regardless, I'll look into whether it could be as a result of the `__get_context_getter` implementation. In the meantime, @krauss, do you also observe this error if you open a Subscription outside of the GraphiQL interface?

**Comment by krauss** [comment] 2022-11-29 18:40
I do. My front-end, a Vue.js based application which uses Apollo client to consume my GraphQL API, is experiencing the same issue. Although we send the custom header "Authorization" in the subscription, nothing comes up in the back-end.

**Comment by tsmith023** [comment] 2022-11-30 21:01
@krauss, I believe that the error you're encountering is as a result of the Websockets API exposed within the browser. If you inspect the console in the browser you'll see that your custom headers aren't even being attached to the request.

![Screenshot from 2022-11-29 21-40-10](https://user-images.githubusercontent.com/66489849/204904091-ce5285ba-c023-4727-b920-3245820c3415.png)

It seems that custom headers are not added to websocket request by the browser: https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api, and so you will have to find another way to do token-based authentication.

If the Apollo-client for Vue.js uses the native Websocket API under-the-hood then it may also be the reason why you're having this problem there. The Apollo.js ecosystem tackles this problem by sending a `connectionParams` object from the client to the server via an ApolloLink. However, `connectionParams` is not an option currently supported by Strawberry.

My personal recommendation would be to implement HTTP-only cookies for the passing of authentication credentials from clients to APIs: https://stackoverflow.com/questions/22285299/use-session-data-on-websocket-handshake. Besides the fact that this will work for websockets, it is also much more secure as JWTs won't be lying around in your user's `localStorage` ready to be hijacked by malicious actors. I think JWTs should only be used in b2b communications, but some may disagree with me on this one!

In terms of duplicating the Apollo functionality of `connectionParams`, we can discuss this as a future feature of the Strawberry offering. :grin: Finally, do you feel this problem could be alleviated by a change to the documentation?

**Comment by DoctorJohn** [comment] 2022-11-30 21:31
> However, connectionParams is not an option currently supported by Strawberry.

Connection params are actually supported by strawberry, they are part of the graphql over websocket specification we implement. The connection params can be accessed by subclassing the `GraphQLTransportWSHandler`. Here is an example with the aiohttp integration but it basically works the same with other integrations:

```python
from strawberry.aiohttp.handlers import GraphQLTransportWSHandler
from strawberry.aiohttp.views import GraphQLView

class CustomGraphQLTransportWSHandler(GraphQLTransportWSHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.token = None

    async def handle_connection_init(self, message) -> None:
        connection_params = message.payload or {}
        self.token = connection_params.get("token")
        return await super().handle_connection_init(message)

    async def get_context(self):
        context = await super().get_context()
        context["token"] = self.token
        return context

class GraphQLHandler(GraphQLView):
    graphql_transport_ws_handler_class = CustomGraphQLTransportWSHandler

```

**Comment by tsmith023** [comment] 2022-11-30 23:19
@DoctorJohn
That's great news, thanks for letting me know!

@krauss
I'll open a PR that implements this as a feature of the FastAPI integration and hopefully get it merged in the coming days.

**Comment by krauss** [comment] 2022-12-01 11:59
Hey @tsmith023, thanks for you reply.

> Finally, do you feel this problem could be alleviated by a change to the documentation?

Yes I do. But look, I know you guys have explicitly said that on the docs: "Authentication is not currently Strawberry's responsibility". However, on the Permission page, there could be a note saying that custom headers are not added to Subscriptions. So anyone trying to implement token-based authentication/authorization, like me, would know this limitation before hand.

> I'll open a PR that implements this as a feature of the FastAPI integration and hopefully get it merged in the coming days.

Thank you all @DoctorJohn, @tsmith023 for the effort! I will try to use `connectionParams` as soon as it becomes available.

**Comment by DoctorJohn** [comment] 2022-12-01 12:28
Hey @krauss,

Connection params are already useable. I used them in production for almost a year now :) I updated the example I posted somewhere above to directly work with fastapi. 

Their accessibility could be improved I guess. But personally I don't mind that one has to create subclasses. Documenting the process would help tho. :)

**Comment by tsmith023** [comment] 2022-12-01 12:37
> However, on the Permission page, there could be a note saying that custom headers are not added to Subscriptions

I think it would be useful to include this in the documentation since it's a significant issue that's likely to trip-up more people.

However, I'd like to be clear here that the issue is not with Strawberry but instead with the native browser Websocket client. When I run Strawberry's unit tests, any custom header that is defined programatically there is correctly ingested into the context object.

The documentation addition should be one that details how to use `connectionParams` in a Subscriptions request and not a detailed analysis of why custom headers, not including cookies, won't be passed from browsers to APIs over websockets.

**Closed** 2023-01-13 15:29 UTC
Labels: bug
