### ISSUE TITLE
Unable to make a generic resolver (how to make a reusable resolver)?

### ISSUE THREAD

**Issue by invokermain** [strawberry-graphql/strawberry#1887] opened 2022-05-06 16:20 UTC
## Describe the Bug

Schema raises exception when working with a generic resolver:

```
TypeError: Query fields cannot be resolved. The type "<strawberry.type.StrawberryTypeVar object at 0x0000012E1A32BCD0>" is generic, but no type has been passed
```

## System Information

 - Operating system: Windows 11/Python 3.10
 - Strawberry version (if applicable): 0.111

## Additional Context

MRE:

```python
from typing import Callable, Type, TypeVar

import strawberry


@strawberry.type
class MyItemType:
    my_int: int
    my_str: str


T = TypeVar("T")


def does_not_work(strawberry_type: Type[T]) -> Callable[..., T]:
    def normal_resolver() -> T:
        return MyItemType(my_int=3, my_str="a")

    return normal_resolver


def also_does_not_work(strawberry_type: Type[T]) -> Callable[..., T]:
    def normal_resolver() -> T:
        return strawberry_type(my_int=3, my_str="a")

    return normal_resolver


def does_work():
    def normal_resolver():
        return MyItemType(my_int=3, my_str="a")

    return normal_resolver


def also_works(strawberry_type):
    def normal_resolver():
        return strawberry_type(my_int=3, my_str="a")

    return normal_resolver


@strawberry.type
class Query:
    my_item: MyItemType = strawberry.field(does_not_work(MyItemType))


@strawberry.type
class Query2:
    my_item: MyItemType = strawberry.field(also_does_not_work(MyItemType))


@strawberry.type
class Query3:
    my_item: MyItemType = strawberry.field(does_work)


@strawberry.type
class Query4:
    my_item: MyItemType = strawberry.field(also_works(MyItemType))


if __name__ == "__main__":
    strawberry.Schema(Query)  # raises a Type Error

    strawberry.Schema(Query2)  # raises a Type Error

    strawberry.Schema(Query3)  # all good

    strawberry.Schema(Query4)  # all good
```

Hello, it seems that this library is unable to support generic resolvers. The type hints seem to cause a runtime error, while without type hints there is no problem (leading me to believe it's a library issue and not a Python typing limitation?).

Is this a bug? Is there a recommended way of making a 'resolver factory'?

Thanks!

**Comment by invokermain** [comment] 2022-05-06 20:00
So it looks like this is possible, just type hinting it breaks it. I can use something like this for SQLModel/Pydantic/FastAPI set up:

```python
def resolve_get(
    strawberry_type: Any,
    sql_model: Type[SQLModel],
):
    def resolver_(item_id: int):
        with Session(ENGINE.engine) as session:
            out = session.get(sql_model, item_id)
            if out is not None:
                return strawberry_type.from_pydantic(out)
            else:
                return out

    return resolver_

@strawberry.type
class Query:
    document: Optional[DocumentType] = strawberry.field(
        resolve_get(DocumentType, Document)
    )
```

**Comment by patrick91** [comment] 2022-05-06 22:54
Hi @invokermain, thanks for the report! 

it looks like currently we give priority to the returned type of the resolver, which causes this issue. I can't remember why we did that, so I think we can change to always use the type specified in the object type.

We wanted to throw a warning/issue if the field and resolver types weren't compatible btw.

I'll add this issue to the monthly work, so hopefully I'll get to it soon, unless you want to try and make a PR 😊

**Comment by invokermain** [comment] 2022-05-07 10:46
Happy to take a stab at it if you have any pointers. The debugger was not very fruitful when I was analysing the above.

I see the benefit of the early warning system (apart from when you get false positives like this one 😃).

Is a possible solution:

`StrawberryTypeVar` (which I am guessing is the correct generic?) is treated the same as Any in that case? I.e. let's just trust that it is the correct return type (it's definitely more correct than Any), if it's not it will get caught when the api is queried.

As in:

This should work
```python
def resolver_factory(strawberry_type: Type[T]) -> Callable[..., T]:
    def normal_resolver() -> T:
        return strawberry_type(my_int=3, my_str="a")

    return normal_resolver
```

But this should still raise an error?
```python
def bad_resolver_factory(strawberry_type) -> Callable[..., SomeIncorrectType]:
    def normal_resolver():
        return strawberry_type(my_int=3, my_str="a")

    return normal_resolver
```

**Comment by invokermain** [comment] 2022-05-07 10:48
I also raised [a similar report](https://github.com/strawberry-graphql/strawberry/discussions/1885) as a discussion (it was more of a question as to how to type hint resolvers in general).

**Comment by patrick91** [comment] 2022-05-07 14:34
> But this should still raise an error?
> 
> ```python
> def bad_resolver_factory(strawberry_type) -> Callable[..., SomeIncorrectType]:
>     def normal_resolver():
>         return strawberry_type(my_int=3, my_str="a")
> 
>     return normal_resolver
> ```

in theory yes, but it won't raise an error if you're not specifying the return in the resolver

This is how I think the resolver/field type matrix should behave

| field type | resolver return type | current behaviour      | expected behaviour                   | current type | expected type |
|------------|----------------------|------------------------|--------------------------------------|--------------|---------------|
| int        | TypeVar("T")         | runtime error          | no error [1]                         | int          | int           |
| int        | int                  | no errors, no warnings | no errors, no warnings               | int          | int           |
| int        | missing              | no errors, no warning  | no error, maybe a (opt-out) warning? | int          | int           |
| int        | str                  | no errors, no warnings | error                                | str          | int           |

this is where we resolve the types for fields: https://github.com/strawberry-graphql/strawberry/blob/c3fe83b939529a2b8fcbd8ea363b2c8fa0d1be35/strawberry/field.py#L200-L220

[1] though we might want to find a way to error out if the actual return type is wrong

**Comment by invokermain** [comment] 2022-05-07 14:50
Cool, I'll see if I can contribute/start off a PR towards this issue tonight

**Comment by invokermain** [comment] 2022-05-08 11:36
[This commit](https://github.com/invokermain/strawberry/commit/d01428bf0fbfbf7db97f80850b436458ff4e2897) has a fix for the generic resolver, and a test.

**Comment by patrick91** [comment] 2022-05-08 16:35
> [This commit](https://github.com/invokermain/strawberry/commit/d01428bf0fbfbf7db97f80850b436458ff4e2897) has a fix for the generic resolver, and a test. Can open a PR if you are happy with it.

Sure!

> I'm guessing the other missing behaviour from the matrix (the `int/str` case) would sit better in a separate PR?

Yes, I'll make an issue for this when your PR is merged 😊

**Comment by invokermain** [comment] 2022-05-08 17:33
Cool PR opened

**Comment by patrick91** [comment] 2022-05-09 22:20
Closing in favour of #1896

**Closed by patrick91** 2022-05-09 22:20 UTC
Labels: bug
