### ISSUE TITLE
Importing Strawberry fails

### ISSUE THREAD

**Issue by tbarnier** [strawberry-graphql/strawberry#626] opened 2020-12-26 12:26 UTC
`bug.py`

```python
#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import strawberry

@strawberry.type
class Token:
    text: str
    begin: int
    end: int
    typ: str

schema = strawberry.Schema(query=Token)
print(schema)
```

error message:

```bash
$ ./bug.py 
Traceback (most recent call last):
  File "./bug.py", line 4, in <module>
    import strawberry
  File "/.venv/lib/python3.8/site-packages/strawberry/__init__.py", line 1, in <module>
    from . import experimental, federation
  File "/.venv/lib/python3.8/site-packages/strawberry/federation.py", line 17, in <module>
    from strawberry.schema.types.types import TypeMap
  File "/.venv/lib/python3.8/site-packages/strawberry/schema/__init__.py", line 2, in <module>
    from .schema import Schema as Schema
  File "/.venv/lib/python3.8/site-packages/strawberry/schema/schema.py", line 14, in <module>
    from ..printer import print_schema
  File "/.venv/lib/python3.8/site-packages/strawberry/printer.py", line 5, in <module>
    from graphql.utilities.print_schema import (
ModuleNotFoundError: No module named 'graphql.utilities.print_schema'
```

**Comment by jkimbo** [comment] 2020-12-26 13:26
@tbarnier do you have a folder called `graphql` in your project?

**Comment by tbarnier** [comment] 2020-12-26 16:22
Yes :(

thanks for your help :)

**Comment by tbarnier** [comment] 2020-12-26 16:35
Apparently the `graphql.utilities.print_schema` module exists only since version 3.1.0, before then it was `schema_printer`

**Comment by BryceBeagle** [comment] 2020-12-27 08:24
I closed this issue as it appear to be solved. If this is incorrect feel free to reopen.

**Comment by ulgens** [comment] 2020-12-27 08:39
@BryceBeagle There is a PR to solve this issue, i don't think it's solved yet.

**Comment by BryceBeagle** [comment] 2020-12-27 08:41
Oh you're right. I think misread @tbarnier's response. I thought their problem was caused by a local directory, and that the `graphql.utilities.print_schema` was a separate issue. I'll repoen.

**Closed** 2021-01-23 21:52 UTC
