### ISSUE TITLE
`from __future__ import annotations` incompatible with `strawberry.Private`

### ISSUE THREAD

**Issue by rjgildea** [strawberry-graphql/strawberry#1586] opened 2022-01-22 00:56 UTC
Using a minor variation from the [getting started tutorial](https://strawberry.rocks/docs) (addition of `from __future__ import annotations` and the use of `strawberry.Private`) results in a traceback. The code works as expected when commenting out the `from __future__` import.

```
from __future__ import annotations

import typing
import strawberry

@strawberry.type
class Book:
    title: str
    author: str
    
    foo: strawberry.Private[int]


def get_books():
    return [
        Book(
            title='The Great Gatsby',
            author='F. Scott Fitzgerald',
            foo=1,
        ),
    ]


@strawberry.type
class Query:
    books: typing.List[Book] = strawberry.field(resolver=get_books)


schema = strawberry.Schema(query=Query)
```

Starting the built-in strawberry server results in the following traceback:
```
$ strawberry server schema
Traceback (most recent call last):
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/graphql/type/definition.py", line 735, in fields
    fields = resolve_thunk(self._fields)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/graphql/type/definition.py", line 264, in resolve_thunk
    return thunk() if callable(thunk) else thunk
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 280, in get_graphql_fields
    graphql_fields[field_name] = self.from_field(field)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 136, in from_field
    field_type = self.from_non_optional(field.type)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 261, in from_non_optional
    of_type = self.from_type(type_)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/strawberry/schema/schema_converter.py", line 469, in from_type
    raise TypeError(f"Unexpected type '{type_}'")
TypeError: Unexpected type 'typing.Annotated[int, <strawberry.private.StrawberryPrivate object at 0x7f72dcd2b820>]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/project/virtualenv/bin/strawberry", line 8, in <module>
    sys.exit(run())
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/strawberry/cli/commands/server.py", line 46, in server
    schema_symbol = import_module_symbol(schema, default_symbol_name="schema")
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/strawberry/utils/importer.py", line 15, in import_module_symbol
    module = importlib.import_module(module_name)
  File "/dls_sw/apps/mamba/0.19.1/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/path/to/project/./schema.py", line 29, in <module>
    schema = strawberry.Schema(query=Query)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/strawberry/schema/schema.py", line 84, in __init__
    self._schema = GraphQLSchema(
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/graphql/type/schema.py", line 208, in __init__
    collect_referenced_types(query)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/graphql/type/schema.py", line 423, in collect_referenced_types
    collect_referenced_types(field.type)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/graphql/type/schema.py", line 422, in collect_referenced_types
    for field in named_type.fields.values():
  File "/dls_sw/apps/mamba/0.19.1/lib/python3.10/functools.py", line 970, in __get__
    val = self.func(instance)
  File "/path/to/project/virtualenv/lib/python3.10/site-packages/graphql/type/definition.py", line 737, in fields
    raise TypeError(f"{self.name} fields cannot be resolved. {error}")
TypeError: Book fields cannot be resolved. Unexpected type 'typing.Annotated[int, <strawberry.private.StrawberryPrivate object at 0x7f72dcd2b820>]'
```

Python version:
```
$ python
Python 3.10.1 | packaged by conda-forge | (main, Dec 22 2021, 01:39:05) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

Strawberry version:
```
$ pip show strawberry-graphql
Name: strawberry-graphql
Version: 0.94.0
Summary: A library for creating GraphQL APIs
Home-page: https://strawberry.rocks/
Author: Patrick Arminio
Author-email: patrick.arminio@gmail.com
License: MIT
Location: /path/to/project/virtualenv/lib/python3.10/site-packages
Requires: python-multipart, backports.cached-property, click, graphql-core, python-dateutil, pygments, typing_extensions, sentinel
Required-by: 
```

OS: RHEL7.9

**Comment by thejaminator** [comment] 2022-01-23 14:43
this is because `from __future__ import annotations` makes the types disappear and it just becomes a string at runtime. we should be able to actual type. [though i know pydantic had lots of problems with it.](https://github.com/samuelcolvin/pydantic/issues/2678) lemme try it out.

**Comment by BryceBeagle** [comment] 2022-01-25 15:38
Very easy to reproduce. This should be considered a bug.
```python
import strawberry

@strawberry.type
class PrivateForward:
    not_seen: "strawberry.Private[int]"

strawberry.Schema(query=PrivateForward)
```

I'm investigating this now

**Comment by cpontvieux-systra** [comment] 2022-01-31 10:26
`annotations` from future implies to resolve types later, so it’s perfectly normal that the return type is a string.

This behavior was scheduled to be included by default with Python 3.10 but was postponed for this reason: multiple libraries are not compatible with it.

To make this work, one should add code to resolve the type from string: https://www.python.org/dev/peps/pep-0563/#resolving-type-hints-at-runtime

**Comment by cpontvieux-systra** [comment] 2022-01-31 10:31
```python
from typing import get_type_hints
class A:
    ...
class B:
    def toto() -> A:
        ...
print(B.toto.__annotations__)
print(get_type_hints(B.toto))
```
Returns:
```
{'return': <class '__main__.A'>}
{'return': <class '__main__.A'>}
```

```python
from __future__ import annotations
from typing import get_type_hints
class A:
    ...
class B:
    def toto() -> A:
        ...
print(B.toto.__annotations__)
print(get_type_hints(B.toto))
```
Returns:
```
{'return': 'A'}
{'return': <class '__main__.A'>}
```

**Comment by patrick91** [comment] 2022-01-31 15:47
> To make this work, one should add code to resolve the type from string: https://www.python.org/dev/peps/pep-0563/#resolving-type-hints-at-runtime

We do this already :) unfortunately we do check for Private before that happens, so we need to refactor the check to make it work properly :)

**Comment by skilkis** [comment] 2022-02-11 02:08
Examining this problem I came to the following conclusion: If one creates a schema where the `Private` field type refers to a class defined after the decorated class, then runtime type resolution during construction of the `StrawberryField` would fail. This is because the referred class does not yet exist in the module namespace. For example:

```python

from __future__ import annotations

import strawberry

@strawberry.type
class Foo:
    bar: strawberry.Private[Quz]

class Quz:
   pass
```

In the above, when `_get_fields` is called by `strawberry.type` the class `Quz` does not yet exist in the module namespace.
To counteract this problem, I think the check for `Private` fields should to be delayed to when the actual schema is built. A potential solution implementing this approach would be to modify `GraphQLCoreConverter.from_object()` with a call to `is_private` like so:

```python
    def from_object(self, object_type: TypeDefinition) -> GraphQLObjectType:
        ...
        def get_graphql_fields() -> Dict[str, GraphQLField]:
            graphql_fields = {}

            for field in object_type.fields:
                if not is_private(field.type):
                    field_name = self.config.name_converter.from_field(field)

                    graphql_fields[field_name] = self.from_field(field)

            return graphql_fields
```

To avoid duplication, the checks for private fields in `_get_fields` could be removed I think. Please, let me know if I missed something @patrick91 @BryceBeagle. If you like this solution, I would be happy to write up a PR 😄

**Comment by thejaminator** [comment] 2022-02-15 17:27
thanks @skilkis ! @BryceBeagle is now working on the solution, he'll update this soon

**Comment by skilkis** [comment] 2022-02-25 14:50
@BryceBeagle I don't want to step on your toes here. I really needed this fix for my current work and wanted to contribute to resolving this issue. Feel free to reject the PR if you want to implement a different solution! Cheers 🍺

**Comment by BryceBeagle** [comment] 2022-02-27 00:49
Hey @skilkis, thanks for working on this, and sorry for the delay. Don't fear about stepping on my toes; I hadn't found a working solution to the problem yet. I'll take a look at your PR tonight :+1:

**Closed** 2022-03-08 04:23 UTC
Labels: bug
