### ISSUE TITLE
Raise an exception if creating a type with the same name

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#404] opened 2020-08-01 17:36 UTC
See https://github.com/strawberry-graphql/strawberry/pull/403/files#r463982907 for context.

Right now when creating a type we check if it is already in our type schema, if it is there we use it, but we don't check for duplicates

**Comment by Kommandat** [comment] 2021-05-28 19:36
Hey @patrick91, I'd like to start contributing to Strawberry and this looks like a good first issue to tackle. Any advice on how to get started and where to look?

My understanding is we would want to raise an exception if someone has duplicate types. A test could look like:

```
def test_raises_exception_with_duplicate_types():
    @strawberry.type
    class Query:
        title: str
        age: int

    @strawberry.type
    class Query:
        title: str
        age: int

    with pytest.raises(
        TypeError, match="Schema contains duplicate types named 'Book'"
    ):
        strawberry.Schema(query=Query)
```

**Comment by BryceBeagle** [comment] 2021-05-28 19:46
Hi @Kommandat! Thanks for your interest. There's a big PR refactor coming down the pipeline (#906) that's going to completely change how the internal typing system is handled. It's been a long time coming, but I'm aiming to have it done really soon. 

I'd hold off on this issue for now. There's a potential that PR ends up resolving this issue.

**Comment by Kommandat** [comment] 2021-05-28 20:19
Thanks @BryceBeagle! I'll hold off then. Let me know if there are any other issues you know of where I can lend a hand.

**Comment by coady** [comment] 2022-12-02 01:42
#2356 has caused a regression with generic types. Subscripted types are being counted as "duplicates".
```python
T = TypeVar("T")

@strawberry.type
class A(Generic[T]):
    a: T

@strawberry.type
class Query:
    first: A[int]
    second: A[int]

strawberry.Schema(Query)  # raises TypeError... Duplicated type name: IntA
```

**Comment by patrick91** [comment] 2022-12-02 11:15
@coady thanks! I'll take a look :)

**Closed** 2022-12-02 12:15 UTC
Labels: enhancement, good first issue
