### ISSUE TITLE
AttributeError: 'str' object has no attribute 'isoformat' for Pydantic Models

### ISSUE THREAD

**Issue by navyamehta** [strawberry-graphql/strawberry#1252] opened 2021-09-15 13:33 UTC
I'm using a strawberry model defined from an underlying Pydantic model that has a date field. However, when I try to initialize the model with a `string` for the date (say "2020-09-17") instead of a datetime object, it errors out with `AttributeError: 'str' object has no attribute 'isoformat'`.

**Comment by patrick91** [comment] 2021-09-16 09:32
@navyamehta do you have a small reproduction case? :)

**Comment by navyamehta** [comment] 2021-09-16 21:43
A basic example is this:
```
import strawberry
from datetime import datetime

@strawberry.type
class MyModel:
     a_field: datetime

@strawberry.type
class MainQuery:
     def a_resolver(self) -> MyModel:
           return MyModel(a_field="2020-09-17 00:00:00+00")
```
And the query can be:
```
query {
    a_resolver {
       a_field
   }
}
```
When interacting with this via Postman, my query errors out with `AttributeError: 'str' object has no attribute 'isoformat'`, presumably since Strawberry tries to format dates before returning to client. Hope this makes sense!

**Comment by patrick91** [comment] 2021-09-16 22:23
This is expected, you need to pass a datetime instance, for example:

```
@strawberry.type
class MainQuery:
     def a_resolver(self) -> MyModel:
           return MyModel(a_field=datetime.now())
```

**Comment by navyamehta** [comment] 2021-09-17 01:08
Oh I was under the impression therr was auto type casting when such casts were feasible. Thanks for the clarification!

**Comment by DoctorJohn** [comment] 2021-09-22 22:02
Looks like this has been resolved 🎉 I'll close this issue now :)

**Closed by DoctorJohn** 2021-09-22 22:02 UTC
