### ISSUE TITLE
directives

### ISSUE THREAD

**Issue by musavirchukkan** [strawberry-graphql/strawberry#214] opened 2019-11-17 04:58 UTC
Our changelog has this example for directives:

import strawberry
from strawberry.directives import DirectiveLocation

@strawberry.type
class Query:
    cake: str = "made_in_switzerland"

@strawberry.directive(
    locations=[DirectiveLocation.FIELD], description="Make string uppercase"
)
def uppercase(value: str, example: str):
    return value.upper()

schema = strawberry.Schema(query=Query, directives=[uppercase])

but we don't have strawberry.directives package :)

**Comment by jaydenwindle** [comment] 2019-11-18 16:23
Duplicate of #169. Please don't open new issues that are word-for-word duplicates of existing (closed) issues :)

**Closed by jaydenwindle** 2019-11-18 16:23 UTC
