### ISSUE TITLE
Import for apollo tracing extension requires telemetry

### ISSUE THREAD

**Issue by patrick91** [strawberry-graphql/strawberry#565] opened 2020-11-10 20:37 UTC
If you do:

```
from strawberry.extensions.tracing import ApolloTracingExtension
```

You will get this error:

```
ModuleNotFoundError: No module named 'opentelemetry'
```

**Comment by benwis** [comment] 2020-12-08 16:56
This appears to be caused by an opentelemetry import in strawberry/extensions__init__.py

I commented out the import and it appears to start now.

**Comment by navyamehta** [comment] 2021-11-16 19:52
Was wondering if there would be a fix for this (maybe not importing those extensions in __init__) for the issue?

**Comment by patrick91** [comment] 2021-11-16 20:38
@navyamehta I think we need a custom [`__getattr__` for the module](https://www.python.org/dev/peps/pep-0562/), so we don't break backwards compatibility :D

**Closed** 2022-07-06 11:16 UTC
Labels: bug, good first issue, Hacktoberfest
